apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
        - name: my-python-app
          image: gcr.io/suresh-jenkins-project/my-python-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000